### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by sahilbabbar** [rush-skills/tedxiiitd#1]
This is what I saw on refreshing the page after the tickets were closed => I was logged in from someone else's email id!
![screen shot 2015-03-30 at 11 02 04 pm](https://cloud.githubusercontent.com/assets/6317330/6902353/002db286-d731-11e4-8b00-ae947e749a34.png)

**Comment by rush-skills** [comment]
Yeah it happened due to some session -> id mapping as we switched databases in background. We will make sure that wont happen again.
